package com.github.dsquare68.homeforge.db;

import java.time.Instant;

/**
 * The PostgreSQL login HUB provisions for a single plugin at install time.
 *
 * <p>Written by {@link HubDBProvider} into {@code <plugin_id>.properties} inside
 * the plugin's own jar, so the plugin can load it as a classpath resource and
 * build its own DataSource:
 *
 * <pre>{@code
 * Properties props = new Properties();
 * try (InputStream in = getClass().getResourceAsStream("/gym.properties")) {
 *     props.load(in);
 * }
 * }</pre>
 *
 * @param pluginId        plugin id from the jar manifest, e.g. {@code gym}
 * @param schema          schema the role owns, e.g. {@code gym_schema}
 * @param role            generated login role, e.g. {@code plugin_gym}
 * @param password        randomly generated password, never reused across plugins
 * @param url             JDBC URL with {@code currentSchema} pinned to {@link #schema()}
 * @param driverClassName JDBC driver the plugin should use
 */
public record PluginDbCredentials(
        String pluginId,
        String schema,
        String role,
        String password,
        String url,
        String driverClassName) {

    /** Property keys as they appear in {@code <plugin_id>.properties}. */
    public static final String KEY_URL = "db.url";
    public static final String KEY_USERNAME = "db.username";
    public static final String KEY_PASSWORD = "db.password";
    public static final String KEY_SCHEMA = "db.schema";
    public static final String KEY_DRIVER = "db.driver-class-name";

    /**
     * Renders the file content HUB writes into the plugin jar. Written by hand
     * rather than {@link java.util.Properties#store} so the ordering and the
     * header stay stable and reviewable.
     */
    public String toFileContent() {
        return """
                # Generated by HUB at %s — do not edit, do not commit.
                # Connection scoped to schema '%s'; this role has no access to
                # hub_schema or any other plugin's schema.
                %s=%s
                %s=%s
                %s=%s
                %s=%s
                %s=%s
                """.formatted(
                Instant.now(),
                schema,
                KEY_URL, url,
                KEY_USERNAME, role,
                KEY_PASSWORD, password,
                KEY_SCHEMA, schema,
                KEY_DRIVER, driverClassName);
    }
}
